"""make api_token.media_id nullable

Revision ID: 6f314b75096e
Revises: 8357d12eb496
Create Date: 2026-04-25 09:07:36.518157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f314b75096e'
down_revision = '8357d12eb496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.alter_column('scopes',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('media_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.alter_column('media_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('scopes',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
