"""add show_offline_banner to display

Revision ID: 8357d12eb496
Revises: 
Create Date: 2026-04-25 08:24:12.295668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8357d12eb496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_offline_banner', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display', schema=None) as batch_op:
        batch_op.drop_column('show_offline_banner')

    # ### end Alembic commands ###
