"""Create or update server/config.py with HTTP/HTTPS deploy presets."""

from __future__ import annotations

import argparse
import os
import re
import secrets
import sys

from deploy_modes import MODES, client_url_hint, describe_mode, resolve_deploy_settings

CONFIG_PATH = os.path.join(os.path.dirname(__file__), 'config.py')


def generate_secret_key() -> str:
    return secrets.token_urlsafe(32)


def _prompt(text: str, default: str = '') -> str:
    suffix = f' [{default}]' if default else ''
    try:
        value = input(f'{text}{suffix}: ').strip()
    except EOFError:
        value = ''
    return value or default


def _prompt_mode(default: str = 'http') -> str:
    print('\nHow will clients reach this server?\n')
    for key in ('http', 'https'):
        preset = MODES[key]
        print(f"  {key}  — {preset['label']}")
        print(f"       {preset['description']}\n")
    while True:
        choice = _prompt('Enter mode (http or https)', default).lower()
        if choice in MODES:
            return choice
        print('Please enter "http" or "https".')


def _interactive_options(default_mode: str = 'http') -> dict:
    mode = _prompt_mode(default_mode if default_mode in MODES else 'http')
    hostname = _prompt(
        'Public hostname for clients (optional — e.g. signage.example.com)',
    )
    proxy_hops = 1
    if mode == 'https':
        behind_cdn = _prompt('Behind Cloudflare or another CDN in front of nginx? (y/N)', 'n').lower()
        if behind_cdn in ('y', 'yes'):
            proxy_hops = 2
    return {
        'mode': mode,
        'hostname': hostname or None,
        'proxy_hops': proxy_hops,
        'secret': generate_secret_key(),
    }


def render_config(
    *,
    mode: str,
    secret: str,
    hostname: str | None = None,
    proxy_hops: int | None = None,
) -> str:
    settings = resolve_deploy_settings(mode, proxy_hops=proxy_hops, server_name=hostname)
    server_name_literal = repr(settings['SERVER_NAME'])
    return f"""# AISignX server configuration
# Generated by: python generate_config.py
# Docs: docs/SERVER_HTTP_ONLY_or_HTTPS_ONLY_Version2.md
#
# Switch modes: edit AISIGNX_DEPLOY_MODE below ('http' or 'https') and restart,
# or re-run: python generate_config.py --interactive --force

import os

from deploy_modes import resolve_deploy_settings

AISIGNX_DEPLOY_MODE = {settings['AISIGNX_DEPLOY_MODE']!r}

_deploy = resolve_deploy_settings(
    AISIGNX_DEPLOY_MODE,
    proxy_hops={settings['TRUST_PROXY_HOPS']},
    server_name={server_name_literal},
)

SECRET_KEY = os.environ.get('AISIGNX_SECRET_KEY', {secret!r})

_db_path = os.environ.get('AISIGNX_DB_PATH')
SQLALCHEMY_DATABASE_URI = (
    os.environ.get('AISIGNX_DATABASE_URI')
    or (f'sqlite:///{{_db_path}}' if _db_path else 'sqlite:///digital_signage.db')
)
SQLALCHEMY_TRACK_MODIFICATIONS = False
UPLOAD_FOLDER = os.environ.get('UPLOAD_FOLDER', 'uploads')
MAX_CONTENT_LENGTH = 100 * 1024 * 1024  # 100 MB
PLUGINS_DIR = os.environ.get('PLUGINS_DIR', 'plugins')

TRUST_PROXY = _deploy['TRUST_PROXY']
TRUST_PROXY_HOPS = int(os.environ.get('TRUST_PROXY_HOPS', str(_deploy['TRUST_PROXY_HOPS'])))
PREFERRED_URL_SCHEME = os.environ.get('PREFERRED_URL_SCHEME', _deploy['PREFERRED_URL_SCHEME'])
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', str(_deploy['SESSION_COOKIE_SECURE']).lower()).lower() in ('1', 'true', 'yes')
REMEMBER_COOKIE_SECURE = os.environ.get('REMEMBER_COOKIE_SECURE', str(_deploy['REMEMBER_COOKIE_SECURE']).lower()).lower() in ('1', 'true', 'yes')

SERVER_NAME = os.environ.get('AISIGNX_SERVER_NAME') or _deploy.get('SERVER_NAME')
"""


def write_config(
    *,
    mode: str,
    secret: str | None = None,
    hostname: str | None = None,
    proxy_hops: int | None = None,
) -> None:
    secret = secret or generate_secret_key()
    content = render_config(mode=mode, secret=secret, hostname=hostname, proxy_hops=proxy_hops)
    with open(CONFIG_PATH, 'w', encoding='utf-8') as f:
        f.write(content)


def read_existing_mode() -> str | None:
    if not os.path.exists(CONFIG_PATH):
        return None
    with open(CONFIG_PATH, encoding='utf-8') as f:
        text = f.read()
    match = re.search(r"AISIGNX_DEPLOY_MODE\s*=\s*['\"](\w+)['\"]", text)
    return match.group(1) if match else None


def read_existing_hostname() -> str | None:
    if not os.path.exists(CONFIG_PATH):
        return None
    with open(CONFIG_PATH, encoding='utf-8') as f:
        match = re.search(r"server_name=(['\"]?)([^,'\"\n]+)\1", f.read())
    if not match or match.group(2) in ('None', 'null'):
        return None
    return match.group(2)


def normalize_mode(mode: str | None) -> str:
    value = (mode or 'http').strip().lower()
    if value not in MODES:
        print(f'Unknown mode {value!r}; using http.', file=sys.stderr)
        return 'http'
    return value


def show_config() -> int:
    mode = read_existing_mode()
    if not mode:
        print(f'No deploy mode found in {CONFIG_PATH}')
        return 1
    hostname = read_existing_hostname()
    print(describe_mode(mode))
    print(f'Client URL hint: {client_url_hint(mode, hostname)}')
    print(f'Config file: {CONFIG_PATH}')
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description='Generate AISignX server/config.py with HTTP or HTTPS presets.',
    )
    parser.add_argument('--mode', choices=sorted(MODES), help='http (direct) or https (reverse proxy)')
    parser.add_argument('--interactive', '-i', action='store_true', help='Guided setup wizard')
    parser.add_argument('--force', '-f', action='store_true', help='Overwrite existing config.py')
    parser.add_argument('--hostname', help='Public hostname (e.g. signage.example.com)')
    parser.add_argument('--proxy-hops', type=int, help='Proxy hops (2 = Cloudflare -> nginx)')
    parser.add_argument('--show', action='store_true', help='Show current deploy mode')
    return parser


def _print_summary(mode: str, hostname: str | None) -> None:
    print(f'\nWrote {CONFIG_PATH}')
    print(describe_mode(mode))
    print(f'Client URL hint: {client_url_hint(mode, hostname)}')
    if mode == 'https':
        print('\nNext: put nginx/Caddy/IIS on port 443 -> http://127.0.0.1:5000')
        print('See docs/PRODUCTION_DEPLOYMENT.md for examples.')
    else:
        print('\nStart the server: python app.py')
        print('Admin UI: http://localhost:5000')


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.show:
        return show_config()

    if os.path.exists(CONFIG_PATH) and not args.force:
        print(f'Config already exists at {CONFIG_PATH}')
        print('Use --show to view mode, or --interactive --force to regenerate.')
        return 0

    env_mode = os.environ.get('AISIGNX_DEPLOY_MODE', 'http')
    hostname: str | None = args.hostname
    proxy_hops: int | None = args.proxy_hops
    secret: str | None = None

    use_interactive = args.interactive or (
        args.mode is None and sys.stdin.isatty() and not os.environ.get('AISIGNX_DEPLOY_MODE')
    )

    if use_interactive:
        opts = _interactive_options(args.mode or env_mode)
        mode = opts['mode']
        hostname = opts['hostname']
        proxy_hops = opts['proxy_hops']
        secret = opts['secret']
    else:
        mode = normalize_mode(args.mode or env_mode)

    write_config(mode=mode, secret=secret, hostname=hostname, proxy_hops=proxy_hops)
    _print_summary(mode, hostname)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
