# Install Caddy and generate deploy\Caddyfile for HTTPS in front of AISignX.
# Run from server/:  powershell -ExecutionPolicy Bypass -File scripts\setup_https.ps1
#
#   -Hostname signage.example.com
#   -Email admin@example.com          # optional, for Let's Encrypt account
#   -InstallService                   # register Windows service (needs Admin)

param(
    [string]$Hostname = $env:AISIGNX_HOSTNAME,
    [string]$Email = $env:AISIGNX_EMAIL,
    [switch]$InstallService,
    [switch]$NonInteractive
)

$ErrorActionPreference = 'Stop'
$ServerDir = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$DeployDir = Join-Path $ServerDir 'deploy'
$Caddyfile = Join-Path $DeployDir 'Caddyfile'

if (-not $Hostname) {
    $Hostname = $env:COMPUTERNAME
    if (-not $Hostname) { $Hostname = 'localhost' }
}

function Test-InternalTls {
    param([string]$Name)
    if ($Name -match '^(localhost|127\.0\.0\.1|::1)$') { return $true }
    if ($Name -like '*.local') { return $true }
    if ($Name -match '^\d{1,3}(\.\d{1,3}){3}$') { return $true }
    return $false
}

function Write-Caddyfile {
    $internal = Test-InternalTls $Hostname
    New-Item -ItemType Directory -Force -Path $DeployDir | Out-Null
    $stamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
    if ($internal) {
        Write-Host '[!] Using Caddy internal TLS (browser warning once; not a public CA).' -ForegroundColor Yellow
        @"
# Generated by setup_https.ps1 — $stamp
$Hostname {
    tls internal
    reverse_proxy 127.0.0.1:5000
}
"@ | Set-Content -Path $Caddyfile -Encoding UTF8
    } else {
        Write-Host '[OK] Automatic Let''s Encrypt for ' $Hostname -ForegroundColor Green
        Write-Host '[!] DNS must point here; ports 80 and 443 open.' -ForegroundColor Yellow
        if ($Email) {
            @"
# Generated by setup_https.ps1 — $stamp
{
    email $Email
}

$Hostname {
    reverse_proxy 127.0.0.1:5000
}
"@ | Set-Content -Path $Caddyfile -Encoding UTF8
        } else {
            @"
# Generated by setup_https.ps1 — $stamp
$Hostname {
    reverse_proxy 127.0.0.1:5000
}
"@ | Set-Content -Path $Caddyfile -Encoding UTF8
        }
    }
    Write-Host "[OK] Wrote $Caddyfile" -ForegroundColor Green
}

function Ensure-Caddy {
    if (Get-Command caddy -ErrorAction SilentlyContinue) {
        Write-Host "[OK] Caddy: $(caddy version 2>&1 | Select-Object -First 1)" -ForegroundColor Green
        return
    }
    Write-Host '[*] Installing Caddy via winget...' -ForegroundColor Yellow
    try {
        winget install --id Caddy.Caddy -e --accept-source-agreements --accept-package-agreements
    } catch {
        Write-Host '[FAIL] winget install failed. Download: https://caddyserver.com/download' -ForegroundColor Red
        throw
    }
    $env:Path = [System.Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' +
        [System.Environment]::GetEnvironmentVariable('Path', 'User')
    if (-not (Get-Command caddy -ErrorAction SilentlyContinue)) {
        throw 'Caddy not on PATH after install. Open a new terminal or add Caddy to PATH.'
    }
}

Write-Host ''
Write-Host 'AISignX HTTPS setup (Caddy)' -ForegroundColor Cyan
Write-Host ''
Write-Caddyfile

$internal = Test-InternalTls $Hostname
if ($NonInteractive) {
    try { Ensure-Caddy } catch { Write-Host '[!] Install Caddy manually if needed.' -ForegroundColor Yellow }
} else {
    $ans = Read-Host 'Install Caddy now if missing? [Y/n]'
    if ($ans -notmatch '^[Nn]') {
        Ensure-Caddy
    }
}

if ($InstallService) {
    Ensure-Caddy
    $caddyExe = (Get-Command caddy).Source
    & $caddyExe stop 2>$null
    & $caddyExe uninstall 2>$null
    & $caddyExe install --config $Caddyfile
    & $caddyExe start
    Write-Host "[OK] Caddy Windows service started (https://$Hostname/)" -ForegroundColor Green
} else {
    Write-Host ''
    Write-Host 'Next steps:' -ForegroundColor Green
    Write-Host '  1. AISignX on 127.0.0.1:5000 (python app.py or waitress-serve --host=127.0.0.1 --port=5000 app:app)'
    Write-Host '  2. Run Caddy as Administrator (port 443):'
    Write-Host "     cd $ServerDir"
    Write-Host "     caddy run --config deploy\Caddyfile"
    Write-Host "  3. Admin UI: https://$Hostname/"
    if ($internal) {
        Write-Host '  For a free trusted certificate, use a public hostname: -Hostname signage.example.com'
    }
    Write-Host ''
    Write-Host 'Service install (Admin): scripts\setup_https.ps1 -Hostname ... -InstallService' -ForegroundColor Gray
}
