#!/usr/bin/env bash
# Install Caddy and generate a Caddyfile so AISignX is served over HTTPS.
# AISignX stays on http://127.0.0.1:5000; Caddy proxies https://HOST -> backend.
#
# Usage (from server/):
#   chmod +x scripts/setup_https.sh
#   ./scripts/setup_https.sh --hostname signage.example.com
#   ./scripts/setup_https.sh --hostname localhost
#   sudo ./scripts/setup_https.sh --hostname signage.example.com --system
#
# Environment:
#   AISIGNX_HOSTNAME   — same as --hostname
#   AISIGNX_EMAIL      — optional ACME account email (recommended for production)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOY_DIR="$SERVER_DIR/deploy"
CADDYFILE="$DEPLOY_DIR/Caddyfile"
HOSTNAME="${AISIGNX_HOSTNAME:-}"
EMAIL="${AISIGNX_EMAIL:-}"
USE_SYSTEM=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --hostname|-h) HOSTNAME="$2"; shift 2 ;;
        --email|-e)    EMAIL="$2"; shift 2 ;;
        --system)      USE_SYSTEM=1; shift ;;
        --help)
            sed -n '2,12p' "$0"
            exit 0
            ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

if [[ -z "$HOSTNAME" ]]; then
    HOSTNAME="$(hostname -f 2>/dev/null || hostname 2>/dev/null || echo localhost)"
    HOSTNAME="${HOSTNAME%%.*}"
    if [[ -z "$HOSTNAME" || "$HOSTNAME" == "(none)" ]]; then
        HOSTNAME="localhost"
    fi
fi

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
info()  { echo -e "${YELLOW}[*]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
fail()  { echo -e "${RED}[FAIL]${NC} $*"; exit 1; }

needs_internal_tls() {
    case "$HOSTNAME" in
        localhost|127.0.0.1|::1) return 0 ;;
    esac
    [[ "$HOSTNAME" == *.local ]] && return 0
    [[ "$HOSTNAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] && return 0
    return 1
}

write_caddyfile() {
    mkdir -p "$DEPLOY_DIR"
    if needs_internal_tls; then
        warn "Using Caddy internal TLS for $HOSTNAME (not a public CA cert)."
        warn "Browsers will show a one-time security warning — accept to enable offline caching."
        cat > "$CADDYFILE" <<EOF
# Generated by setup_https.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
$HOSTNAME {
    tls internal
    reverse_proxy 127.0.0.1:5000
}
EOF
    else
        ok "Using automatic Let's Encrypt for $HOSTNAME (free trusted certificate)."
        warn "Requires: DNS A/AAAA for $HOSTNAME -> this server, ports 80 and 443 open to the internet."
        if [[ -n "$EMAIL" ]]; then
            cat > "$CADDYFILE" <<EOF
# Generated by setup_https.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
{
    email $EMAIL
}

$HOSTNAME {
    reverse_proxy 127.0.0.1:5000
}
EOF
        else
            cat > "$CADDYFILE" <<EOF
# Generated by setup_https.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
$HOSTNAME {
    reverse_proxy 127.0.0.1:5000
}
EOF
        fi
    fi
    ok "Wrote $CADDYFILE"
}

install_caddy() {
    if command -v caddy &>/dev/null; then
        ok "Caddy already installed: $(caddy version 2>/dev/null | head -1)"
        return
    fi
    info "Installing Caddy..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        command -v brew &>/dev/null || fail "Install Homebrew from https://brew.sh then re-run."
        brew install caddy
    elif command -v apt-get &>/dev/null; then
        sudo apt-get update -qq
        sudo apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
        sudo apt-get update -qq
        sudo apt-get install -y caddy
    elif command -v dnf &>/dev/null; then
        sudo dnf install -y 'dnf-command(copr)' || true
        sudo dnf copr enable -y @caddy/caddy 2>/dev/null || true
        sudo dnf install -y caddy || fail "Install Caddy manually: https://caddyserver.com/docs/install"
    else
        fail "Unsupported OS. Install Caddy from https://caddyserver.com/docs/install"
    fi
    ok "Caddy installed."
}

install_systemd() {
    [[ "$USE_SYSTEM" -eq 1 ]] || return
    [[ "$(id -u)" -eq 0 ]] || fail "--system requires root (sudo)."
    install_caddy
    cp "$CADDYFILE" /etc/caddy/Caddyfile
    systemctl enable caddy
    systemctl restart caddy
    ok "Caddy systemd service enabled (https://$HOSTNAME)."
}

echo -e "\n${CYAN}AISignX HTTPS setup (Caddy)${NC}\n"
write_caddyfile

if [[ "$USE_SYSTEM" -eq 1 ]]; then
    install_systemd
else
    if ! command -v caddy &>/dev/null; then
        if [[ "$(id -u)" -eq 0 ]] || command -v apt-get &>/dev/null || [[ "$OSTYPE" == "darwin"* ]]; then
            ans="Y"
            if [[ -t 0 ]] && [[ "${AISIGNX_NONINTERACTIVE:-}" != "1" ]]; then
                read -r -p "Install Caddy now? [Y/n] " ans || ans="Y"
            fi
            if [[ ! "$ans" =~ ^[Nn] ]]; then
                install_caddy || warn "Caddy install failed — install manually."
            fi
        else
            warn "Caddy not found. Install it, then run:"
            echo "  cd $SERVER_DIR && caddy run --config deploy/Caddyfile"
        fi
    fi
    echo ""
    ok "Next steps:"
    echo "  1. Start AISignX on 127.0.0.1:5000 (install script or: waitress-serve --host=127.0.0.1 --port=5000 app:app)"
    echo "  2. Start Caddy:"
    echo "       cd $SERVER_DIR"
    if needs_internal_tls; then
        echo "       sudo caddy run --config deploy/Caddyfile   # port 443 needs root on Linux"
    else
        echo "       sudo caddy run --config deploy/Caddyfile"
    fi
    echo "  3. Open admin UI: https://$HOSTNAME/"
    echo ""
    echo "  Production: sudo $SCRIPT_DIR/setup_https.sh --hostname $HOSTNAME --system"
    if needs_internal_tls; then
        echo "  For a free trusted cert, use a public DNS name and re-run with --hostname your.domain"
    fi
fi
