"""phase1_initial_schema

Revision ID: 53a8dc53ac78
Revises: 
Create Date: 2026-04-30 11:28:36.196321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a8dc53ac78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('branding_logo_path', sa.String(length=255), nullable=True),
    sa.Column('branding_primary_color', sa.String(length=16), nullable=True),
    sa.Column('storage_quota_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('default_timezone', sa.String(length=64), nullable=True),
    sa.Column('retention_policy', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_slug'), ['slug'], unique=True)

    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_key'), ['key'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('background_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_job_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_job_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_job_status'), ['status'], unique=False)
        batch_op.create_index('ix_job_status_created', ['status', 'created_at'], unique=False)

    op.create_table('display_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sync_playback', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('display_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_display_group_domain_id'), ['domain_id'], unique=False)

    op.create_table('emergency_broadcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('background_color', sa.String(length=20), nullable=True),
    sa.Column('text_color', sa.String(length=20), nullable=True),
    sa.Column('target', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('cleared_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cleared_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_broadcast', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_broadcast_domain_id'), ['domain_id'], unique=False)

    op.create_table('emergency_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('background_color', sa.String(length=20), nullable=True),
    sa.Column('text_color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_template_domain_id'), ['domain_id'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('codec', sa.String(length=40), nullable=True),
    sa.Column('bitrate_bps', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('original_variant_key', sa.String(length=16), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_external_id'), ['external_id'], unique=True)

    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fallback_playlist_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fallback_playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_domain_id'), ['domain_id'], unique=False)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'name', name='uq_role_domain_name')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_domain_id'), ['domain_id'], unique=False)

    op.create_table('system_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'key', name='uq_setting_domain_key')
    )
    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_setting_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_setting_key'), ['key'], unique=False)

    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('scopes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('oauth_client_id', sa.String(length=64), nullable=True),
    sa.Column('oauth_client_secret', sa.String(length=256), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_token_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_token_oauth_client_id'), ['oauth_client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_token_token_hash'), ['token_hash'], unique=True)

    op.create_table('display',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_ping', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('resolution_x', sa.Integer(), nullable=True),
    sa.Column('resolution_y', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('aspect_mode', sa.String(length=20), nullable=True),
    sa.Column('show_media_buttons', sa.Boolean(), nullable=False),
    sa.Column('allow_input', sa.Boolean(), nullable=False),
    sa.Column('show_offline_banner', sa.Boolean(), nullable=False),
    sa.Column('unlock_pin', sa.String(length=8), nullable=True),
    sa.Column('current_content', sa.String(length=200), nullable=True),
    sa.Column('current_playlist_item_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['display_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('display', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_display_api_key'), ['api_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_display_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_display_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_display_group_id'), ['group_id'], unique=False)

    op.create_table('playlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('aspect_mode', sa.String(length=20), nullable=True),
    sa.Column('plugin_type', sa.String(length=50), nullable=True),
    sa.Column('plugin_config', sa.JSON(), nullable=True),
    sa.Column('clip_start', sa.Float(), nullable=True),
    sa.Column('clip_end', sa.Float(), nullable=True),
    sa.Column('mute_audio', sa.Boolean(), nullable=False),
    sa.Column('transition', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_item_playlist_id'), ['playlist_id'], unique=False)

    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_domain_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'domain_id', 'role_id', name='uq_udr')
    )
    with op.batch_alter_table('user_domain_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_domain_role_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_domain_role_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_domain_role_user_id'), ['user_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_api_token_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['actor_api_token_id'], ['api_token.id'], ),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_ts', ['action', 'timestamp'], unique=False)
        batch_op.create_index('ix_audit_domain_ts', ['domain_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_audit_user_ts', ['actor_user_id', 'timestamp'], unique=False)

    op.create_table('pending_display',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('friendly_name', sa.String(length=120), nullable=True),
    sa.Column('hostname', sa.String(length=120), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('display_id', sa.Integer(), nullable=True),
    sa.Column('approved_domain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['display_id'], ['display.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_display', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_display_device_id'), ['device_id'], unique=True)

    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('days_of_week', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['display_id'], ['display.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['display_group.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_domain_id'), ['domain_id'], unique=False)

    op.create_table('display_schedule',
    sa.Column('display_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['display_id'], ['display.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('display_id', 'schedule_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('display_schedule')
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_domain_id'))

    op.drop_table('schedule')
    with op.batch_alter_table('pending_display', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_display_device_id'))

    op.drop_table('pending_display')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_ts')
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_domain_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))
        batch_op.drop_index('ix_audit_domain_ts')
        batch_op.drop_index('ix_audit_action_ts')

    op.drop_table('audit_log')
    with op.batch_alter_table('user_domain_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_domain_role_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_domain_role_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_domain_role_domain_id'))

    op.drop_table('user_domain_role')
    op.drop_table('role_permission')
    with op.batch_alter_table('playlist_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_item_playlist_id'))

    op.drop_table('playlist_item')
    with op.batch_alter_table('display', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_display_group_id'))
        batch_op.drop_index(batch_op.f('ix_display_domain_id'))
        batch_op.drop_index(batch_op.f('ix_display_device_id'))
        batch_op.drop_index(batch_op.f('ix_display_api_key'))

    op.drop_table('display')
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_api_token_oauth_client_id'))
        batch_op.drop_index(batch_op.f('ix_api_token_domain_id'))

    op.drop_table('api_token')
    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_setting_key'))
        batch_op.drop_index(batch_op.f('ix_system_setting_domain_id'))

    op.drop_table('system_setting')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_domain_id'))

    op.drop_table('role')
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_domain_id'))

    op.drop_table('playlist')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_external_id'))
        batch_op.drop_index(batch_op.f('ix_media_domain_id'))
        batch_op.drop_index(batch_op.f('ix_media_checksum_sha256'))

    op.drop_table('media')
    with op.batch_alter_table('emergency_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_template_domain_id'))

    op.drop_table('emergency_template')
    with op.batch_alter_table('emergency_broadcast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_broadcast_domain_id'))

    op.drop_table('emergency_broadcast')
    with op.batch_alter_table('display_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_display_group_domain_id'))

    op.drop_table('display_group')
    with op.batch_alter_table('background_job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_status_created')
        batch_op.drop_index(batch_op.f('ix_background_job_status'))
        batch_op.drop_index(batch_op.f('ix_background_job_kind'))
        batch_op.drop_index(batch_op.f('ix_background_job_domain_id'))

    op.drop_table('background_job')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_key'))

    op.drop_table('permission')
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_slug'))

    op.drop_table('domain')
    # ### end Alembic commands ###
